const knowledgeDB = {
  "quantum mechanics": ["Wave Function","Superposition","Entanglement","Schrödinger Equation","Heisenberg Uncertainty","Planck Constant","Photon","Quantum Field Theory"],
  "wave function": ["Probability Amplitude","Hilbert Space","Schrödinger Equation","Quantum State","Born Rule"],
  superposition: ["Quantum Computing","Wave Function","Interference","Qubit","Decoherence"],
  entanglement: ["Bell Theorem","Quantum Teleportation","EPR Paradox","Nonlocality","Quantum Computing"],
  "schrödinger equation": ["Wave Function","Hamiltonian","Eigenvalue","Quantum State","Potential Energy"],
  "heisenberg uncertainty": ["Measurement Problem","Observer Effect","Complementarity","Wave–Particle Duality"],
  "planck constant": ["Quantum","Photon","Energy","Black-Body Radiation","Photoelectric Effect"],
  photon: ["Electromagnetic Radiation","Light","Quantum Electrodynamics","Laser","Wave–Particle Duality"],
  "quantum field theory": ["Standard Model","Feynman Diagram","Renormalization","Gauge Theory","Higgs Boson"],
  renaissance: ["Humanism","Leonardo da Vinci","Michelangelo","Printing Press","Florence","Perspective Art","Reformation","Galileo"],
  humanism: ["Renaissance","Classical Antiquity","Petrarch","Liberal Arts","Secularism"],
  "leonardo da vinci": ["Mona Lisa","Anatomy","Engineering","Renaissance","Polymath","Painting"],
  michelangelo: ["Sistine Chapel","Sculpture","Renaissance","David","Architecture"],
  "printing press": ["Gutenberg","Movable Type","Book","Reformation","Information Revolution"],
  florence: ["Medici","Renaissance","Tuscany","Cathedral","Machiavelli"],
  galileo: ["Telescope","Heliocentrism","Physics","Jupiter","Scientific Method"],
  "artificial intelligence": ["Machine Learning","Neural Network","Deep Learning","Natural Language Processing","Computer Vision","Turing Test","Robotics","Ethics of AI"],
  "machine learning": ["Supervised Learning","Neural Network","Gradient Descent","Overfitting","Random Forest","Feature Extraction"],
  "neural network": ["Deep Learning","Backpropagation","Perceptron","Convolutional NN","Activation Function"],
  "deep learning": ["Transformer","GPT","GAN","Reinforcement Learning","TensorFlow","Neural Network"],
  "natural language processing": ["Transformer","Word Embedding","Sentiment Analysis","GPT","BERT","Tokenization"],
  transformer: ["Attention Mechanism","GPT","BERT","Self-Attention","Deep Learning"],
  "computer vision": ["Convolutional NN","Object Detection","Image Recognition","Deep Learning","Feature Extraction"],
  "turing test": ["Alan Turing","Artificial Intelligence","Consciousness","Chinese Room"],
  "black holes": ["Event Horizon","Singularity","Hawking Radiation","General Relativity","Accretion Disk","Spacetime","Gravity","Neutron Star"],
  "event horizon": ["Schwarzschild Radius","Black Holes","Spacetime","Light","Escape Velocity"],
  singularity: ["Big Bang","General Relativity","Black Holes","Infinity","Quantum Gravity"],
  "hawking radiation": ["Stephen Hawking","Black Holes","Quantum Mechanics","Thermodynamics","Virtual Particles"],
  "general relativity": ["Einstein","Spacetime","Gravity","Gravitational Waves","Curved Space"],
  spacetime: ["General Relativity","Minkowski Space","Light Cone","Dimension","Time Dilation"],
  philosophy: ["Metaphysics","Epistemology","Ethics","Logic","Aesthetics","Existentialism","Plato","Aristotle"],
  metaphysics: ["Ontology","Reality","Consciousness","Free Will","Determinism"],
  epistemology: ["Knowledge","Empiricism","Rationalism","Skepticism","Justification"],
  ethics: ["Morality","Utilitarianism","Deontology","Virtue Ethics","Justice"],
  existentialism: ["Sartre","Kierkegaard","Absurdism","Freedom","Authenticity"],
  plato: ["Republic","Forms","Socrates","Academy","Allegory of the Cave"],
  aristotle: ["Logic","Metaphysics","Nicomachean Ethics","Biology","Poetics"],
  dna: ["Gene","Double Helix","RNA","Chromosome","Protein","Mutation","CRISPR","Genome"],
  gene: ["DNA","Allele","Genotype","Phenotype","Heredity","Expression"],
  "double helix": ["Watson and Crick","DNA","Base Pair","Nucleotide","Rosalind Franklin"],
  rna: ["mRNA","Ribosome","Transcription","DNA","Protein Synthesis"],
  crispr: ["Gene Editing","Cas9","DNA","Biotechnology","Jennifer Doudna"],
  mutation: ["Evolution","DNA","Gene","Natural Selection","Genetic Disorder"],
  evolution: ["Natural Selection","Darwin","Adaptation","Speciation","Fossil Record","Genetics"],
  "natural selection": ["Evolution","Fitness","Darwin","Adaptation","Survival"],
  darwin: ["Origin of Species","Evolution","Natural Selection","Galápagos","Biology"],
};
const EXAMPLES = ["Quantum Mechanics","Renaissance","Artificial Intelligence","Black Holes","Philosophy","DNA","Evolution"];
const RANDOM_TOPICS = ["Quantum Mechanics","Renaissance","Artificial Intelligence","Black Holes","Philosophy","DNA","Evolution","Photon","Deep Learning","Existentialism","General Relativity","CRISPR","Plato","Aristotle","Florence","Galileo","Transformer","Natural Selection","Darwin"];

export { knowledgeDB, EXAMPLES, RANDOM_TOPICS };